name: Build LG V30 Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: TosteRino/joan-kernelsu
          path: joan-kernelsu

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl xz-utils \
            build-essential ccache \
            libncurses5-dev libssl-dev libelf-dev \
            bison flex bc python3 \
            clang lld llvm \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi

      - name: Enable ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: joan-kernelsu-ccache
          max-size: 5G

      - name: Apply Droidspaces patches
        working-directory: joan-kernelsu
        run: |
          wget -q -O d1.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/main/Documentation/resources/kernel-patches/non-GKI/01.fix_kernel_panic_in_xt_qtaguid.patch
          curl -sL -o d2.patch "https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/main/Documentation/resources/kernel-patches/non-GKI/02.fix_restore%20cgroup%20file%20prefix%20handling%20.patch"
          patch -p1 < d1.patch
          patch -p1 < d2.patch
