name: Large Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - run: |
          echo "line1"
          echo "line2"
          echo "line3"
          echo "line4"
          echo "line5"
          echo "line6"
          echo "line7"
          echo "line8"
          echo "line9"
          echo "line10"
          echo "line11"
          echo "line12"
          echo "line13"
          echo "line14"
          echo "line15"
          echo "line16"
          echo "line17"
          echo "line18"
          echo "line19"
          echo "line20"
          echo "line21"
          echo "line22"
          echo "line23"
          echo "line24"
          echo "line25"
          echo "line26"
          echo "line27"
          echo "line28"
          echo "line29"
          echo "line30"
          echo "line31"
          echo "line32"
          echo "line33"
          echo "line34"
          echo "line35"
          echo "line36"
          echo "line37"
          echo "line38"
          echo "line39"
          echo "line40"
          echo "line41"
          echo "line42"
          echo "line43"
          echo "line44"
          echo "line45"
          echo "line46"
          echo "line47"
          echo "line48"
          echo "line49"
          echo "line50"
          echo "line51"
          echo "line52"
          echo "line53"
          echo "line54"
          echo "line55"
          echo "line56"
          echo "line57"
          echo "line58"
          echo "line59"
          echo "line60"
          echo "line61"
          echo "line62"
          echo "line63"
          echo "line64"
          echo "line65"
          echo "line66"
          echo "line67"
          echo "line68"
          echo "line69"
          echo "line70"
          echo "line71"
          echo "line72"
          echo "line73"
          echo "line74"
          echo "line75"
          echo "line76"
          echo "line77"
          echo "line78"
          echo "line79"
          echo "line80"
          echo "line81"
          echo "line82"
          echo "line83"
          echo "line84"
          echo "line85"
          echo "line86"
          echo "line87"
          echo "line88"
          echo "line89"
          echo "line90"
          echo "line91"
          echo "line92"
          echo "line93"
          echo "line94"
          echo "line95"
          echo "line96"
          echo "line97"
          echo "line98"
          echo "line99"
          echo "line100"
          - run: echo "line101"
          - run: echo "line102"
          - run: echo "line103"
          - run: echo "line104"
          - run: echo "line105"
          - run: echo "line106"
          - run: echo "line107"
          - run: echo "line108"
          - run: echo "line109"
          - run: echo "line110"
          - run: echo "line111"
          - run: echo "line112"
          - run: echo "line113"
          - run: echo "line114"
          - run: echo "line115"
          - run: echo "line116"
          - run: echo "line117"
          - run: echo "line118"
          - run: echo "line119"
          - run: echo "line120"
          - run: echo "line121"
          - run: echo "line122"
          - run: echo "line123"
          - run: echo "line124"
          - run: echo "line125"
          - run: echo "line126"
          - run: echo "line127"
          - run: echo "line128"
          - run: echo "line129"
          - run: echo "line130"
          - run: echo "line131"
          - run: echo "line132"
          - run: echo "line133"
          - run: echo "line134"
          - run: echo "line135"
          - run: echo "line136"
          - run: echo "line137"
          - run: echo "line138"
          - run: echo "line139"
          - run: echo "line140"
          - run: echo "line141"
          - run: echo "line142"
          - run: echo "line143"
          - run: echo "line144"
          - run: echo "line145"
          - run: echo "line146"
          - run: echo "line147"
          - run: echo "line148"
          - run: echo "line149"
          - run: echo "line150"
          - run: echo "line151"
          - run: echo "line152"
          - run: echo "line153"
          - run: echo "line154"
          - run: echo "line155"
          - run: echo "line156"
          - run: echo "line157"
          - run: echo "line158"
          - run: echo "line159"
          - run: echo "line160"
          - run: echo "line161"
          - run: echo "line162"
          - run: echo "line163"
          - run: echo "line164"
          - run: echo "line165"
          - run: echo "line166"
          - run: echo "line167"
          - run: echo "line168"
          - run: echo "line169"
          - run: echo "line170"
          - run: echo "line171"
          - run: echo "line172"
          - run: echo "line173"
          - run: echo "line174"
          - run: echo "line175"
          - run: echo "line176"
          - run: echo "line177"
          - run: echo "line178"
          - run: echo "line179"
          - run: echo "line180"
          - run: echo "line181"
          - run: echo "line182"
          - run: echo "line183"
          - run: echo "line184"
          - run: echo "line185"
          - run: echo "line186"
          - run: echo "line187"
          - run: echo "line188"
          - run: echo "line189"
          - run: echo "line190"
          - run: echo "line191"
          - run: echo "line192"
          - run: echo "line193"
          - run: echo "line194"
          - run: echo "line195"
          - run: echo "line196"
          - run: echo "line197"
          - run: echo "line198"
          - run: echo "line199"
          - run: echo "line200"
          - run: echo "line201"
          - run: echo "line202"
          - run: echo "line203"
          - run: echo "line204"
          - run: echo "line205"
          - run: echo "line206"
          - run: echo "line207"
          - run: echo "line208"
          - run: echo "line209"
          - run: echo "line210"
          - run: echo "line211"
          - run: echo "line212"
          - run: echo "line213"
          - run: echo "line214"
          - run: echo "line215"
          - run: echo "line216"
          - run: echo "line217"
          - run: echo "line218"
          - run: echo "line219"
          - run: echo "line220"
          - run: echo "line221"
          - run: echo "line222"
          - run: echo "line223"
          - run: echo "line224"
          - run: echo "line225"
          - run: echo "line226"
          - run: echo "line227"
          - run: echo "line228"
          - run: echo "line229"
          - run: echo "line230"
          - run: echo "line231"
          - run: echo "line232"
          - run: echo "line233"
          - run: echo "line234"
          - run: echo "line235"
          - run: echo "line236"
          - run: echo "line237"
          - run: echo "line238"
          - run: echo "line239"
          - run: echo "line240"
          - run: echo "line241"
          - run: echo "line242"
          - run: echo "line243"
          - run: echo "line244"
          - run: echo "line245"
          - run: echo "line246"
          - run: echo "line247"
          - run: echo "line248"
          - run: echo "line249"
          - run: echo "line250"
          - run: echo "line251"
          - run: echo "line252"
          - run: echo "line253"
          - run: echo "line254"
          - run: echo "line255"
          - run: echo "line256"
          - run: echo "line257"
          - run: echo "line258"
          - run: echo "line259"
          - run: echo "line260"
          - run: echo "line261"
          - run: echo "line262"
          - run: echo "line263"
          - run: echo "line264"
          - run: echo "line265"
          - run: echo "line266"
          - run: echo "line267"
          - run: echo "line268"
          - run: echo "line269"
          - run: echo "line270"
          - run: echo "line271"
          - run: echo "line272"
          - run: echo "line273"
          - run: echo "line274"
          - run: echo "line275"
          - run: echo "line276"
          - run: echo "line277"
          - run: echo "line278"
          - run: echo "line279"
          - run: echo "line280"
          - run: echo "line281"
          - run: echo "line282"
          - run: echo "line283"
          - run: echo "line284"
          - run: echo "line285"
          - run: echo "line286"
          - run: echo "line287"
          - run: echo "line288"
          - run: echo "line289"
          - run: echo "line290"
          - run: echo "line291"
          - run: echo "line292"
          - run: echo "line293"
          - run: echo "line294"
          - run: echo "line295"
          - run: echo "line296"
          - run: echo "line297"
          - run: echo "line298"
          - run: echo "line299"
          - run: echo "line300"
